#### Normalizaton
##### Xnew = (Xi - min(X))/(max(X) - min(X))
##### ranging between 0 and 1

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("loan.csv")
dataset.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP00001,Male,Yes,2,Graduate,Yes,16337,7648,574.0,360.0,0.0,Semiurban,N
1,LP00002,NaN,No,0,Graduate,NaN,24986,9550,261.0,360.0,1.0,Rural,Y
2,LP00003,Female,Yes,0,Graduate,No,8812,5115,74.0,NaN,1.0,Semiurban,Y

In [4]:
dataset.isnull().sum()

Loan_ID               0
Gender                9
Married              10
Dependents           10
Education             0
Self_Employed        17
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      7
Credit_History       10
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
dataset.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,100.000000,100.000000,100.00000,93.000000,90.000000
mean,13456.110000,4877.790000,389.50000,267.096774,0.711111
std,6651.114018,2629.982188,196.22485,98.318257,0.455785
min,1509.000000,55.000000,50.00000,120.000000,0.000000
25%,8423.750000,2823.250000,220.00000,180.000000,0.000000
50%,13321.500000,5125.000000,376.50000,360.000000,1.000000
75%,19024.500000,6895.750000,568.75000,360.000000,1.000000
max,24986.000000,9945.000000,699.00000,360.000000,1.000000

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
ms = MinMaxScaler()
ms.fit(dataset[["CoapplicantIncome"]])

MinMaxScaler()

In [10]:
ms.transform(dataset[["CoapplicantIncome"]])

array([[0.7677452 ],
       [0.96006067],
       [0.51162791],
       [0.46329626],
       [0.48523761],
       [0.3156724 ],
       [0.7760364 ],
       [0.2148635 ],
       [0.48907988],
       [0.7065723 ],
       [0.0082912 ],
       [0.63417594],
       [0.34550051],
       [0.54539939],
       [0.28078868],
       [0.35631951],
       [0.59817998],
       [0.41547017],
       [0.79737108],
       [0.55753286],
       [0.42922144],
       [0.62831143],
       [0.38048534],
       [0.18715875],
       [0.62679474],
       [0.07128413],
       [0.78614762],
       [0.73761375],
       [0.62517695],
       [0.61021234],
       [0.60424671],
       [0.77168857],
       [0.91365015],
       [0.99656218],
       [0.85106168],
       [0.18523761],
       [0.32467139],
       [0.06177958],
       [0.41789687],
       [0.06228514],
       [0.67967644],
       [0.75985844],
       [0.79888777],
       [0.51253792],
       [0.55915066],
       [0.47745197],
       [0.38877654],
       [0.66956522],
       [0.70030334],
       [0.63913043],
       [0.04732053],
       [0.2364004 ],
       [0.25662285],
       [1.        ],
       [0.72649141],
       [0.6958544 ],
       [0.62032356],
       [0.52426694],
       [0.65096057],
       [0.28543984],
       [0.41334681],
       [0.36289181],
       [0.44256825],
       [0.12345804],
       [0.58200202],
       [0.02497472],
       [0.05894843],
       [0.        ],
       [0.87583418],
       [0.81850354],
       [0.20930233],
       [0.03124368],
       [0.68291203],
       [0.46167846],
       [0.51274014],
       [0.51233569],
       [0.16086957],
       [0.08725986],
       [0.27724975],
       [0.65227503],
       [0.58796764],
       [0.14924166],
       [0.82072801],
       [0.33265925],
       [0.770273  ],
       [0.69706775],
       [0.69029323],
       [0.18715875],
       [0.30647118],
       [0.81870576],
       [0.57583418],
       [0.89484328],
       [0.10182002],
       [0.1942366 ],
       [0.12548028],
       [0.62426694],
       [0.76703741],
       [0.00707786],
       [0.4627907 ],
       [0.63023256]])

In [12]:
dataset["CoapplicationIncome_min"]=ms.transform(dataset[["CoapplicantIncome"]])
dataset

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,CoapplicationIncome_min
0,LP00001,Male,Yes,2,Graduate,Yes,16337,7648,574.0,360.0,0.0,Semiurban,N,0.767745
1,LP00002,NaN,No,0,Graduate,NaN,24986,9550,261.0,360.0,1.0,Rural,Y,0.960061
2,LP00003,Female,Yes,0,Graduate,No,8812,5115,74.0,NaN,1.0,Semiurban,Y,0.511628
3,LP00004,Female,No,3+,Graduate,No,6820,4637,629.0,180.0,1.0,Urban,Y,0.463296
4,LP00005,Male,NaN,2,Not Graduate,No,14716,4854,443.0,360.0,0.0,Semiurban,N,0.485238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,LP00096,Female,Yes,2,Not Graduate,No,8441,6229,285.0,360.0,0.0,Rural,N,0.624267
96,LP00097,Female,No,3+,Not Graduate,No,24886,7641,383.0,180.0,1.0,Semiurban,Y,0.767037
97,LP00098,Male,No,0,Graduate,Yes,11709,125,425.0,360.0,NaN,Semiurban,Y,0.007078
98,LP00099,Male,No,2,Not Graduate,NaN,19215,4632,508.0,180.0,0.0,Semiurban,Y,0.462791
99,LP00100,Male,No,0,Not Graduate,NaN,22145,6288,186.0,360.0,1.0,Urban,Y,0.630233