### Handling missing value(imputing categorical Data)

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset= pd.read_csv("Data.csv")

In [ ]:
# filling data(not right way to fill)
dataset.fillna(10)

   EmployeeID     Name Department   Age   Salary JoiningDate  PerformanceScore
0         101    Alice         HR  25.0  50000.0  2018-05-21               3.5
1         102      Bob         IT  10.0  60000.0  2019-08-10              10.0
2         103  Charlie         10  30.0     10.0  2020-01-15               4.0
3         104       10    Finance  28.0  58000.0          10               3.8
4         105      Eve         IT  10.0  62000.0  2021-03-12              10.0
5         106    Frank         HR  45.0     10.0  2017-11-01               4.5
6         107    Grace         10  32.0  55000.0          10               3.0
7         108     Hank    Finance  10.0  57000.0  2019-06-23              10.0

In [7]:
# right way(it gives some warning)
# dataset.fillna(method ="bfill")
# axis =1 -->col and axis =0 -->row
dataset.ffill(axis=1)

,EmployeeID,Name,Department,Age,Salary,JoiningDate,PerformanceScore
0,101,Alice,HR,25.0,50000.0,2018-05-21,3.5
1,102,Bob,IT,IT,60000.0,2019-08-10,2019-08-10
2,103,Charlie,Charlie,30.0,30.0,2020-01-15,4.0
3,104,104,Finance,28.0,58000.0,58000.0,3.8
4,105,Eve,IT,IT,62000.0,2021-03-12,2021-03-12
5,106,Frank,HR,45.0,45.0,2017-11-01,4.5
6,107,Grace,Grace,32.0,55000.0,55000.0,3.0
7,108,Hank,Finance,Finance,57000.0,2019-06-23,2019-06-23

In [15]:
#  one way to fill categorical data is by Mode(finding Mode)
dataset["Name"].mode()

0    Alice
Name: Name, dtype: object

In [9]:
dataset["Name"].mode()[0]

'Alice'

In [ ]:
# filling the dataset Name by "Alice"
dataset["Name"].fillna(dataset["Name"].mode()[0],inplace=True)

In [16]:
# collecting object dataType
dataset.select_dtypes(include="object")

      Name Department JoiningDate
0    Alice         HR  2018-05-21
1      Bob         IT  2019-08-10
2  Charlie        NaN  2020-01-15
3    Alice    Finance         NaN
4      Eve         IT  2021-03-12
5    Frank         HR  2017-11-01
6    Grace        NaN         NaN
7     Hank    Finance  2019-06-23

In [17]:
# finding null value
dataset.select_dtypes(include="object").isnull().sum()

Name           0
Department     2
JoiningDate    2
dtype: int64

In [18]:
# using loop fining categorical data
for i in dataset.select_dtypes(include="object").columns:
    print(i)

Name
Department
JoiningDate

In [20]:
for col in dataset.select_dtypes(include="object").columns:
    dataset.loc[:, col] = dataset[col].fillna(dataset[col].mode()[0])

In [ ]:
dataset.isnull().sum()
# it shows that categorical data is filled by mode

EmployeeID          0
Name                0
Department          0
Age                 3
Salary              2
JoiningDate         0
PerformanceScore    3
dtype: int64