#### Cross-Validation - techinque for validating the model efficiency by training it on the subset of input data and testing on previously unseen subset of input data.

##### Methods used for Cross-Validation-
###### (1)Leave p out cross-validation
###### (2)Leave one out cross-validation
###### (3)Holdout cross validation
###### (4)Repeated random subsampling validation
###### (5) k-fold cross-validation
###### (6) Stratified k-fold cross-validation
###### (7)Time Series cross-validation
###### (8)Nested cross validation

#### (1) K-Fold Cross Validation
##### in this dataset is equally partitioned into k subparts or folds. Out of the k-folds or groups for each iteration one group is selected as validation data and the remaining (k-1) groups are selected as training data. (Not suitable for an imbalanced dataset).

#### (2) Stratified K fold CV(Imbalanced data)(sabhi tarah ke classification hona chahiye)
##### in this dataset is equally partitioned into k subparts or folds. Out of the k-folds or groups for each iteration one group is selected as validation data and the remaining (k-1) groups are selected as training data

##### (3)Leave one out - ek data ko training me baaki rest ko testing me (It is slow for large dataset)

##### (4)Leave P out Cross validation - Ek se jayda data ko trainnig me rest ko testing me dalta h (p as validation data and remaining training data)(it is also slow)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv("cgpa_vs_package.csv")
dataset.head(3)

   CGPA  Package(LPA)
0  6.87         12.38
1  9.75         19.96
2  8.66         17.91

In [4]:
x = dataset.iloc[:, :-1]
y = dataset["Package(LPA)"]

In [9]:
new_data = dataset.head(10)
new_data

   CGPA  Package(LPA)
0  6.87         12.38
1  9.75         19.96
2  8.66         17.91
3  7.99         14.55
4  5.78         15.29
5  5.78         12.51
6  5.29          8.20
7  9.33         19.97
8  8.01         14.07
9  8.54         18.65

In [7]:
x_new = new_data.iloc[:, :-1]
y_new = new_data["Package(LPA)"]

In [6]:
from sklearn.model_selection import LeaveOneOut,LeavePOut,KFold,StratifiedKFold

In [ ]:
# Leave One Out Cross Validation
lo = LeaveOneOut()

for train, test in lo.split(x_new,y_new):
    print("Train Index: ",train,"Test Index: ",test)

Train Index:  [1 2 3 4 5 6 7 8 9] Test Index:  [0]
Train Index:  [0 2 3 4 5 6 7 8 9] Test Index:  [1]
Train Index:  [0 1 3 4 5 6 7 8 9] Test Index:  [2]
Train Index:  [0 1 2 4 5 6 7 8 9] Test Index:  [3]
Train Index:  [0 1 2 3 5 6 7 8 9] Test Index:  [4]
Train Index:  [0 1 2 3 4 6 7 8 9] Test Index:  [5]
Train Index:  [0 1 2 3 4 5 7 8 9] Test Index:  [6]
Train Index:  [0 1 2 3 4 5 6 8 9] Test Index:  [7]
Train Index:  [0 1 2 3 4 5 6 7 9] Test Index:  [8]
Train Index:  [0 1 2 3 4 5 6 7 8] Test Index:  [9]

In [10]:
lp = LeavePOut(p=2)

for train, test in lp.split(x_new,y_new):
    print("Train Index: ",train,"Test Index: ",test)

Train Index:  [2 3 4 5 6 7 8 9] Test Index:  [0 1]
Train Index:  [1 3 4 5 6 7 8 9] Test Index:  [0 2]
Train Index:  [1 2 4 5 6 7 8 9] Test Index:  [0 3]
Train Index:  [1 2 3 5 6 7 8 9] Test Index:  [0 4]
Train Index:  [1 2 3 4 6 7 8 9] Test Index:  [0 5]
Train Index:  [1 2 3 4 5 7 8 9] Test Index:  [0 6]
Train Index:  [1 2 3 4 5 6 8 9] Test Index:  [0 7]
Train Index:  [1 2 3 4 5 6 7 9] Test Index:  [0 8]
Train Index:  [1 2 3 4 5 6 7 8] Test Index:  [0 9]
Train Index:  [0 3 4 5 6 7 8 9] Test Index:  [1 2]
Train Index:  [0 2 4 5 6 7 8 9] Test Index:  [1 3]
Train Index:  [0 2 3 5 6 7 8 9] Test Index:  [1 4]
Train Index:  [0 2 3 4 6 7 8 9] Test Index:  [1 5]
Train Index:  [0 2 3 4 5 7 8 9] Test Index:  [1 6]
Train Index:  [0 2 3 4 5 6 8 9] Test Index:  [1 7]
Train Index:  [0 2 3 4 5 6 7 9] Test Index:  [1 8]
Train Index:  [0 2 3 4 5 6 7 8] Test Index:  [1 9]
Train Index:  [0 1 4 5 6 7 8 9] Test Index:  [2 3]
Train Index:  [0 1 3 5 6 7 8 9] Test Index:  [2 4]
Train Index:  [0 1 3 4 6 7 8 9] Test Index:  [2 5]
Train Index:  [0 1 3 4 5 7 8 9] Test Index:  [2 6]
Train Index:  [0 1 3 4 5 6 8 9] Test Index:  [2 7]
Train Index:  [0 1 3 4 5 6 7 9] Test Index:  [2 8]
Train Index:  [0 1 3 4 5 6 7 8] Test Index:  [2 9]
Train Index:  [0 1 2 5 6 7 8 9] Test Index:  [3 4]
Train Index:  [0 1 2 4 6 7 8 9] Test Index:  [3 5]
Train Index:  [0 1 2 4 5 7 8 9] Test Index:  [3 6]
Train Index:  [0 1 2 4 5 6 8 9] Test Index:  [3 7]
Train Index:  [0 1 2 4 5 6 7 9] Test Index:  [3 8]
Train Index:  [0 1 2 4 5 6 7 8] Test Index:  [3 9]
Train Index:  [0 1 2 3 6 7 8 9] Test Index:  [4 5]
Train Index:  [0 1 2 3 5 7 8 9] Test Index:  [4 6]
Train Index:  [0 1 2 3 5 6 8 9] Test Index:  [4 7]
Train Index:  [0 1 2 3 5 6 7 9] Test Index:  [4 8]
Train Index:  [0 1 2 3 5 6 7 8] Test Index:  [4 9]
Train Index:  [0 1 2 3 4 7 8 9] Test Index:  [5 6]
Train Index:  [0 1 2 3 4 6 8 9] Test Index:  [5 7]
Train Index:  [0 1 2 3 4 6 7 9] Test Index:  [5 8]
Train Index:  [0 1 2 3 4 6 7 8] Test Index:  [5 9]
Train Index:  [0 1 2 3 4 5 8 9] Test Index:  [6 7]
Train Index:  [0 1 2 3 4 5 7 9] Test Index:  [6 8]
Train Index:  [0 1 2 3 4 5 7 8] Test Index:  [6 9]
Train Index:  [0 1 2 3 4 5 6 9] Test Index:  [7 8]
Train Index:  [0 1 2 3 4 5 6 8] Test Index:  [7 9]
Train Index:  [0 1 2 3 4 5 6 7] Test Index:  [8 9]

In [ ]:
# nsplit = 5 means kitne part me data jayega test ke liye aur kitne part me training ke liye
kf = KFold(n_splits=5)

for train, test in kf.split(x_new):
    print("Train Index: ",train,"Test Index: ",test)

Train Index:  [2 3 4 5 6 7 8 9] Test Index:  [0 1]
Train Index:  [0 1 4 5 6 7 8 9] Test Index:  [2 3]
Train Index:  [0 1 2 3 6 7 8 9] Test Index:  [4 5]
Train Index:  [0 1 2 3 4 5 8 9] Test Index:  [6 7]
Train Index:  [0 1 2 3 4 5 6 7] Test Index:  [8 9]

In [ ]:
# works only with classification problems(So it will not work here)
skf = StratifiedKFold(n_splits=5)

# for train, test in skf.split(x_new,y_new):
#     print("Train Index: ",train,"Test Index: ",test)

ValueError: Supported target types are: ('binary', 'multiclass'). Got 'continuous' instead.

In [13]:
from sklearn.linear_model import LinearRegression

In [ ]:
# Finding the range of accuracy
from sklearn.model_selection import cross_val_score

In [15]:
# cross_val_score(estimator,features,target,cv=number of splits)
# Or cv = kf or lo or lp or skf (jo bhi use karna ho)
cross_val_score(LinearRegression(),x,y,cv=5)  # 5 means 5 fold cross validation

array([0.72432823, 0.59538214, 0.58612799, 0.78083119, 0.7617466 ])

In [ ]:
# Arranging in sorted manner
p = cross_val_score(LinearRegression(),x,y,cv=5)
p.sort()
p

array([0.58612799, 0.59538214, 0.72432823, 0.7617466 , 0.78083119])

In [18]:
# if use cv = kf or lo or lp or skf
p = cross_val_score(LinearRegression(),x,y,cv=KFold(n_splits=10))
p.sort()
p

array([0.55325086, 0.56663247, 0.60262852, 0.62378358, 0.66540609,
       0.67737083, 0.69043517, 0.76003667, 0.80862273, 0.85558356])