### One Hot Encoding And Dummy Variables

process of converting categorical data(like string, object etc) into numerical data is called Encoding

Basically it is used when there is like YES/NO or Male/Female type data

In [1]:
import pandas as pd

In [4]:
dataset = pd.read_csv("Large_Employee_Data.csv")
dataset.head(10)

,EmployeeID,Name,Department,Age,Salary,JoiningDate,PerformanceScore,Gender,Marital Status,Experience(Years),Education,Location
0,1001,Employee_1,IT,55.0,NaN,01-02-2020,2.6,Male,NaN,6,PhD,Delhi
1,1002,Employee_2,IT,51.0,106209.0,22-08-2017,4.5,Female,NaN,10,PhD,Chennai
2,1003,Employee_3,Marketing,52.0,39084.0,29-10-2016,2.7,Male,Single,11,High School,Chennai
3,1004,Employee_4,HR,57.0,62214.0,28-09-2015,4.6,Female,Single,1,Master,Bangalore
4,1005,Employee_5,IT,36.0,114659.0,11-03-2020,3.4,Male,Single,10,Bachelor,Mumbai
5,1006,Employee_6,Marketing,50.0,37690.0,24-07-2019,4.2,Male,Married,10,Master,Chennai
6,1007,Employee_7,HR,33.0,39693.0,31-05-2019,3.9,Male,Married,6,PhD,Mumbai
7,1008,Employee_8,IT,53.0,97479.0,10-10-2015,3.6,Female,Married,13,PhD,Mumbai
8,1009,Employee_9,IT,50.0,94668.0,31-10-2019,3.1,Female,Single,14,High School,Delhi
9,1010,Employee_10,Finance,41.0,32118.0,06-10-2021,4.0,Male,Single,10,PhD,Chennai

In [10]:
dataset.isnull().sum()

EmployeeID           0
Name                 0
Department           0
Age                  1
Salary               2
JoiningDate          0
PerformanceScore     0
Gender               0
Marital Status       0
Experience(Years)    0
Education            0
Location             0
dtype: int64

In [6]:
# filling dataset(This method may give warning so use below cell method)
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace=True)

In [ ]:

# This is the new method used in new Version of python
dataset["Marital Status"] = dataset["Marital Status"].fillna(dataset["Marital Status"].mode()[0])

In [ ]:
# Before we apply Get dummies we have to select the columns 
en_data = dataset[["Gender","Marital Status"]]
en_data

    Gender Marital Status
0     Male        Married
1   Female        Married
2     Male         Single
3   Female         Single
4     Male         Single
..     ...            ...
95    Male         Single
96    Male        Married
97  Female        Married
98  Female        Married
99    Male        Married

[100 rows x 2 columns]

In [19]:
# One hot Encoding using get Dummy Method
pd.get_dummies(en_data)

    Gender_Female  Gender_Male  Marital Status_Married  Marital Status_Single
0           False         True                    True                  False
1            True        False                    True                  False
2           False         True                   False                   True
3            True        False                   False                   True
4           False         True                   False                   True
..            ...          ...                     ...                    ...
95          False         True                   False                   True
96          False         True                    True                  False
97           True        False                    True                  False
98           True        False                    True                  False
99          False         True                    True                  False

[100 rows x 4 columns]

In [20]:
# Checking in data info
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gender_Female           100 non-null    bool
 1   Gender_Male             100 non-null    bool
 2   Marital Status_Married  100 non-null    bool
 3   Marital Status_Single   100 non-null    bool
dtypes: bool(4)
memory usage: 532.0 bytes

In [ ]:
# From skLearn we are doing one Hot Encoding
from sklearn.preprocessing import OneHotEncoder

In [38]:
# Using one hot encoding (it gives a sparse Matrix)
OnehotEn = OneHotEncoder()
OnehotEn.fit_transform(en_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 200 stored elements and shape (100, 4)>

In [39]:
# Converting into array
arrayData=OnehotEn.fit_transform(en_data).toarray()

In [40]:
pd.DataFrame(arrayData,columns=["Gender_Female","Gender_Male","Marital Status_Married","Marital Status_Single"])

    Gender_Female  Gender_Male  Marital Status_Married  Marital Status_Single
0             0.0          1.0                     1.0                    0.0
1             1.0          0.0                     1.0                    0.0
2             0.0          1.0                     0.0                    1.0
3             1.0          0.0                     0.0                    1.0
4             0.0          1.0                     0.0                    1.0
..            ...          ...                     ...                    ...
95            0.0          1.0                     0.0                    1.0
96            0.0          1.0                     1.0                    0.0
97            1.0          0.0                     1.0                    0.0
98            1.0          0.0                     1.0                    0.0
99            0.0          1.0                     1.0                    0.0

[100 rows x 4 columns]

In [41]:
# Since our dataset become large so to make it smaller we drop first col of each
# OnehotEn = OneHotEncoder(drop="first")
# arrayData=OnehotEn.fit_transform(en_data).toarray()
# arrayData